### ISSUE TITLE
Long tag lines are not processed correctly

### ISSUE THREAD

**Issue by mgmart** [xiaoxinghu/CocoaOrg#5]
Not sure if this is really an issue because also Org-mode had problems with the line. Maybe there is some documented limit on taglines.

Dump below shows the problem:
```
    [3]	SwiftOrg.Section	
    index	SwiftOrg.OrgIndex?
    title	String?	"on level 1.1.1.1                         :tag1:tag2:tag3:tag4: "
    stars	Int	4
    keyword	String?	"TODO"
    priority	SwiftOrg.Section.Priority?	C
    tags	[String]?	nil	none
    content	[Node]	0 values	
```

**Comment by xiaoxinghu** [comment]
@mgmart It's because the trailing spaces. I fixed it, please test again. If everything is OK, will close this. Keep it coming 👍

**Comment by mgmart** [comment]
Don't know when I will able to test again. Assuming you're right :)
Will reopen in the rather unlikely case that it's still present.

Thanks!
